import type { user } from "@server/db/schema";
import { seedIds } from "@server/seed/constants";

type UserInsert = typeof user.$inferInsert;

export const userSeeds: UserInsert[] = [
	{
		id: seedIds.users.alex,
		name: "Alex Popescu",
		email: "alex@urbanpulse.local",
		emailVerified: true,
		image: "https://i.pravatar.cc/300?img=12",
		createdAt: new Date("2026-03-21T08:00:00.000Z"),
		updatedAt: new Date("2026-03-31T10:00:00.000Z"),
		role: "admin",
		bio: "Neighborhood coordinator focused on emergency response and logistics.",
		trustScore: 98,
		successfulInteractions: 38,
		isVerified: true,
		rememberMe: true,
	},
	{
		id: seedIds.users.maria,
		name: "Maria Ionescu",
		email: "maria@urbanpulse.local",
		emailVerified: true,
		image: "https://i.pravatar.cc/300?img=47",
		createdAt: new Date("2026-03-20T11:15:00.000Z"),
		updatedAt: new Date("2026-03-30T18:20:00.000Z"),
		role: "user",
		bio: "Volunteer vet assistant helping with pet rescue alerts.",
		trustScore: 94,
		successfulInteractions: 24,
		isVerified: true,
		rememberMe: true,
	},
	{
		id: seedIds.users.vlad,
		name: "Vlad Dumitru",
		email: "vlad@urbanpulse.local",
		emailVerified: true,
		image: "https://i.pravatar.cc/300?img=21",
		createdAt: new Date("2026-03-22T09:30:00.000Z"),
		updatedAt: new Date("2026-03-30T13:10:00.000Z"),
		role: "user",
		bio: "Paramedic available evenings for urgent transport requests.",
		trustScore: 96,
		successfulInteractions: 31,
		isVerified: true,
		rememberMe: false,
	},
	{
		id: seedIds.users.elena,
		name: "Elena Stan",
		email: "elena@urbanpulse.local",
		emailVerified: true,
		image: "https://i.pravatar.cc/300?img=5",
		createdAt: new Date("2026-03-23T07:40:00.000Z"),
		updatedAt: new Date("2026-03-29T12:45:00.000Z"),
		role: "user",
		bio: "Community teacher organizing local support and resource sharing.",
		trustScore: 92,
		successfulInteractions: 19,
		isVerified: true,
		rememberMe: true,
	},
	{
		id: seedIds.users.irina,
		name: "Irina Matei",
		email: "irina@urbanpulse.local",
		emailVerified: true,
		image: "https://i.pravatar.cc/300?img=31",
		createdAt: new Date("2026-03-24T10:00:00.000Z"),
		updatedAt: new Date("2026-03-30T08:55:00.000Z"),
		role: "user",
		bio: "Tech volunteer helping with communications and coordination.",
		trustScore: 90,
		successfulInteractions: 15,
		isVerified: true,
		rememberMe: false,
	},
	{
		id: seedIds.users.daniel,
		name: "Daniel Marin",
		email: "daniel@urbanpulse.local",
		emailVerified: true,
		image: "https://i.pravatar.cc/300?img=64",
		createdAt: new Date("2026-03-25T12:10:00.000Z"),
		updatedAt: new Date("2026-03-30T16:00:00.000Z"),
		role: "user",
		bio: "Electrician and generator specialist for outage situations.",
		trustScore: 88,
		successfulInteractions: 12,
		isVerified: false,
		rememberMe: false,
	},
];
