export const GLOBAL_CRISIS_RADIUS_METERS = 999_999;
export const GLOBAL_CRISIS_RADIUS_THRESHOLD_METERS = 900_000;

export const DEFAULT_CITY_CENTER = {
	lat: 44.4268,
	lng: 26.1025,
} as const;

export const DEFAULT_LOCAL_CRISIS_RADIUS_METERS = 1_000;
export const MANUAL_CRISIS_EXPIRATION_HOURS = 24;
