export const fakeSkills = [
	{ id: 1, tag: "Fixing Leaky Pipes" },
	{ id: 2, tag: "Unclogging Drains" },
	{ id: 3, tag: "Basic Electrical Repairs" },
	{ id: 4, tag: "Changing Light Fixtures" },
	{ id: 5, tag: "Furniture Assembly" },
	{ id: 6, tag: "Heavy Lifting Help" },
	{ id: 7, tag: "Moving Assistance" },
	{ id: 8, tag: "Car Battery Jumpstart" },
	{ id: 9, tag: "Flat Tire Change" },
	{ id: 10, tag: "Basic Car Diagnostics" },
	{ id: 11, tag: "Grocery Pickup" },
	{ id: 12, tag: "Pet Care Help" },
	{ id: 13, tag: "Cleaning & Tidying" },
	{ id: 14, tag: "Yard Work / Gardening" },
	{ id: 15, tag: "Painting Walls" },
	{ id: 16, tag: "Door Lock Fix" },
	{ id: 17, tag: "Appliance Setup" },
	{ id: 18, tag: "Tech Setup (WiFi, TV)" },
	{ id: 19, tag: "Emergency Ride" },
	{ id: 20, tag: "Package Pickup / Delivery" },
];
